### ISSUE TITLE
When running Decompression test, Assertion `data.size() > 0' failed.

### ISSUE THREAD

**Issue by lrg11** [andybbruno/TSXor#4]
![image](https://user-images.githubusercontent.com/32366608/226971930-ef2a9b37-805f-4d36-bba3-3f7a2e0614c1.png)
It seems that decompression has some problem, Please remind me of the bug location 
Thanks

**Comment by andybbruno** [comment]
Hi @lrg11 👋 
Thanks for creating this issue.

Can you please provide more details about the problem you faced? A great idea would be to share the CSV file you used.

**Comment by lrg11** [comment]
[floats-1w.csv](https://github.com/andybbruno/TSXor/files/11043001/floats-1w.csv)
this is my CSV file
Thanks

**Comment by andybbruno** [comment]
Hey @lrg11 I have good news 😊 

I tried your `csv` file on my Mac and it works fine. In the screenshot below you can see all the steps I've run to execute a complete cycle of compression/decompression. 
 
<img width="952" alt="Screenshot 2023-03-22 at 21 52 37" src="https://user-images.githubusercontent.com/28092511/227036342-4f90075b-a3b9-4d14-bb55-7e2841676f06.png">

**Comment by jermp** [comment]
I've also tried the example with the given CSV file on my mac and I confirm it works on my end too.

**Comment by lrg11** [comment]
![image](https://user-images.githubusercontent.com/32366608/227080839-417ff4e3-0a41-4bfd-a570-4178a0978964.png)
OK, It seems to work on MacOS, while not working on WSL2
Thanks

**Comment by lrg11** [comment]
I have another question, When compressing, is it possible not to record the time window info on the compressed file, as it is always like 0 1 2 3 ...  n

**Comment by andybbruno** [comment]
> OK, I got it, thanks for offering no_ts branch


I actually forgot about it 😂

Anyways thanks for your interest into this project. Please don't forget to star the repository 😉
